/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package a.cache.machine;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(Server.getGreeting(), "app should have a greeting");
    }
}
